Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"

  config.vm.define "k8s-masternode1" do |server|
    config.vm.hostname = "k8s-masternode1"
    server.vm.network "public_network", ip: "192.168.11.71", bridge: "enp4s0"
    config.vm.provision "file", source: "~/.ssh/authorized_keys", destination: ".ssh/authorized_keys_me"
    config.vm.provision "shell" do |s|
    s.inline = <<-SHELL
    cat /home/vagrant/.ssh/authorized_keys_me >> /home/vagrant/.ssh/authorized_keys
    cat /home/vagrant/.ssh/authorized_keys_me >> /root/.ssh/authorized_keys
    SHELL
    end
  end

  config.vm.define "k8s-workernode1" do |server|
    server.vm.network "public_network", ip: "192.168.11.72", bridge: "enp4s0"
    config.vm.hostname = "k8s-workernode1"
    config.vm.provision "file", source: "~/.ssh/authorized_keys", destination: ".ssh/authorized_keys_me"
    config.vm.provision "shell" do |s|
    s.inline = <<-SHELL
    cat /home/vagrant/.ssh/authorized_keys_me >> /home/vagrant/.ssh/authorized_keys
    cat /home/vagrant/.ssh/authorized_keys_me >> /root/.ssh/authorized_keys
    SHELL
    end
  end

  config.vm.define "k8s-workernode2" do |server|
    server.vm.network "public_network", ip: "192.168.11.73", bridge: "enp4s0"
    config.vm.hostname = "k8s-workernode1"
    config.vm.provision "file", source: "~/.ssh/authorized_keys", destination: ".ssh/authorized_keys_me"
    config.vm.provision "shell" do |s|
    s.inline = <<-SHELL
    cat /home/vagrant/.ssh/authorized_keys_me >> /home/vagrant/.ssh/authorized_keys
    cat /home/vagrant/.ssh/authorized_keys_me >> /root/.ssh/authorized_keys
    SHELL
    end
  end
end
